image: node:10.17.0

before_script:
  - yarn install

cache:
  paths:
  - node_modules/
  - .yarn
  
stages:
  - deploy
  
deploy:
  stage: deploy
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    - git push "https://${GITLAB_USER_NAME}:${CI_GIT_TOKEN}@${CI_REPOSITORY_URL#*@}" "HEAD:${CI_COMMIT_TAG}"
   
  