image: node:10.17.0

before_script:
  - yarn install

cache:
  paths:
  - node_modules/
  - .yarn
  
stages:
  - deploy
  
deploy:
  stage: deploy
  script:
    - url_host=$(echo "${CI_REPOSITORY_URL}" | sed -e 's|https\?://gitlab-ci-token:.*@|ssh://git@|g')
    - git remote set-url --push origin "${url_host}"
    - git push "${origin}" HEAD:master
  