image: node:9.4.0

stages:
  - install
  - lint
  - lint-fix
  - test
  - build
  - deploy

before_script:
  - yarn install
  
cache:
  paths:
    - node_modules/
    - .yarn
    
lint:
 stage: lint
 script:
  - yarn run lint

lint-fix:
 stage: lint-fix
 script:
  - yarn run lint-fix

test:
  stage: test
  script:
  - yarn run unit

build:
  stage: build
  script:
   - yarn run build

deploy:
  stage: deploy
  script:
    - git push
  