image: node:10.17.0

before_script:
  - yarn install

cache:
  paths:
  - node_modules/
  - .yarn
  
stages:
  - deploy
  
deploy:
  stage: deploy
  script:
    - git checkout master
    - echo "This is a test" > test.dat
    - git config --global user.email "kushal.m@turtlemint.com"
    - git config --global user.name "Kushal V. Mahajan"
    - git add test.dat
    - git commit -m "Gitlab Runner push"
    - url_host=$(echo "${CI_REPOSITORY_URL}" | sed -e 's|https\?://gitlab-ci-token:.*@|git@|g')
    - git remote set-url --push origin "${url_host}"
    - git push origin HEAD:master
 
  