stages:
  - lint
  - lint-fix
  - test
  - build
  - deploy

lint
 stage: lint
 scripts:
  - yarn run lint

lint-fix
 stage: lint-fix
 scripts:
  - yarn run lint-fix

test
  stage: test
  scripts:
  - yarn run unit

build
  stage: build
  scripts:
   - yarn run build

deploy
  stage: deploy
  scripts:
    - git push
  