image: node:10.17.0

before_script:
  - yarn install

cache:
  paths:
  - node_modules/
  - .yarn
  
stages:
  - lint
  - lint-fix
  - test
  - build

lint:
 stage: lint
 scripts:
  - yarn run lint

lint-fix:
 stage: lint-fix
 scripts:
  - yarn run lint:fix

test:
  stage: test
  scripts:
  - yarn run unit

build:
  stage: build
  scripts:
   - yarn run build

  
# deploy:
#   stage: deploy
#   before_script:
#     - git config --global user.name "${GITLAB_USER_NAME}"
#     - git config --global user.email "${GITLAB_USER_EMAIL}"
#   script:
#     - git push "https://gitlab-ci-token:${CI_GIT_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git" "HEAD:${CI_COMMIT_TAG}"
  